name: Unassign Inactive Issues
description: Unassigns users from issues if they are inactive based on comments or PR activity.

inputs:
  githubToken:
    description: 'GitHub token for authentication'
    required: true
  inactivityPeriodInMinutes:
    description: 'The inactivity threshold in minutes for unassigning an issue'
    required: false
    default: '1'

# runs:
#   using: 'node16'
#   main: './scripts/index.js'
