name: Unassign Inactive Issues
run-name: Unassigns users from issues if they are inactive based on comments or PR activity.

on:
  workflow_call:
    secrets:
      LE_BOT_APP_ID:
        description: "GitHub App ID for authentication"
        required: true
      LE_BOT_PRIVATE_KEY:
        description: "GitHub App Private Key for authentication"
        required: true
      SLACK_WEBHOOK_URL:
        description: "Slack webhook URL for notifications"
        required: true
      
jobs:
  unassign_inactive_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.LE_BOT_APP_ID }}
          private_key: ${{ secrets.LE_BOT_PRIVATE_KEY }}

      - name: Checkout called repository
        uses: actions/checkout@v3
        with:
          repository: SukhvirKooner/.github
          ref: main
          token: ${{ steps.generate-token.outputs.token }}  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install 
      
      - name: Run unassign script
        id: unassign
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const script = require('./scripts/unassign-inactive-issues.js');
            return await script({github, context, core});

      - name: Send Slack notifications
        if: ${{ steps.unassign.outputs.unassignments != '' }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "*\nThe following users have been unassigned due to inactivity:\n${{ steps.unassign.outputs.unassignments }}"
            }