name: Unassign Inactive Issues
run-name: Unassigns users from issues if they are inactive based on comments or PR activity.

on:
  workflow_call:
    secrets:
      WEB_Token:
        description: "GitHub token for authentication"
        required: true
      SLACK_WEBHOOK_URL:
        description: "Slack webhook URL for notifications"
        required: true

permissions:
  issues: write

jobs:
  unassign_inactive_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout called repository
        uses: actions/checkout@v3
        with:
          repository: SukhvirKooner/.github
          ref: main
          token: ${{ secrets.WEB_Token }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Debug directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Scripts directory contents:"
          ls -la scripts
          
      - name: Install dependencies
        run: npm install 
      
      - name: Run unassign script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WEB_Token }}
          script: |
            const script = require('../../scripts/unassign-inactive-issues.js');
            await script({github, context, core});
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}