name: Unassign Inactive Issues

on:
  schedule:
    - cron: '*/10 * * * *' # Adjust this as needed (runs every 10 minutes for testing)

jobs:
  unassign_inactive_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure repository is checked out

      - name: Install dependencies
        run: npm install  # Install dependencies from package.json
      
      - name: Run unassign-inactive-issues action
        uses: ./.github  # Path to the reusable action
        with:
          githubToken: ${{ secrets.WEB_TOKEN }}
          inactivityPeriodInMinutes: 15
