name: Unassign Inactive Issues
run-name: Unassigns users from issues if they are inactive based on comments or PR activity.

on:
  workflow_call:
    inputs:
      inactivityPeriodInMinutes:
        description: "Inactivity period in minutes to trigger unassignment"
        required: true
        type: number
    secrets:
      WEB_Token:
        description: "GitHub token for authentication"
        required: true

jobs:
  unassign_inactive_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install dependencies
        run: cd scripts && npm install

      - name: Run script
        run: cd scripts && node index.js
        env:
          WEB_Token: ${{ secrets.WEB_Token }}
          inactivityPeriodInMinutes: ${{ inputs.inactivityPeriodInMinutes }}