name: Unassign Inactive Issues
description: Unassigns users from issues if they are inactive based on comments or PR activity.
on:
  workflow_call:
    inputs:
      githubToken:
        description: "GitHub token for authentication"
        required: true
      inactivityPeriodInMinutes:
        description: "Inactivity period in minutes to trigger unassignment"
        required: true

jobs:
  unassign_inactive_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./scripts  # Path to the directory with package.json
        run: npm install

      - name: Run unassign-inactive-issues action
        working-directory: ./scripts  # Specify the directory where index.js is located
        run: node index.js
        env:
          githubToken: gihubToken
          inactivityPeriodInMinutes: 15